/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import type { SkillCatalogStartResult, SkillManagerList } from '@deepseek-ai/dsh-skill-manager/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$736b696c6c4d616e61676572 {
    catalogAtStart: (sessionId: SessionId) => Promise<RemoteResult<boolean>>
    list: () => Promise<RemoteResult<SkillManagerList>>
    setCatalogAtStart: (sessionId: SessionId, enabled: boolean) => Promise<RemoteResult<SkillCatalogStartResult>>
    setDisabled: (name: string, disabled: boolean) => Promise<RemoteResult<SkillManagerList>>
  }
  interface TypertRemoteMap {
    'skillManager/catalogAtStart': (sessionId: SessionId) => Promise<RemoteResult<boolean>>
    'skillManager/list': () => Promise<RemoteResult<SkillManagerList>>
    'skillManager/setCatalogAtStart': (sessionId: SessionId, enabled: boolean) => Promise<RemoteResult<SkillCatalogStartResult>>
    'skillManager/setDisabled': (name: string, disabled: boolean) => Promise<RemoteResult<SkillManagerList>>
  }
  interface TypertRemoteNamespaceMap {
    'skillManager': TypertRemoteNamespace$736b696c6c4d616e61676572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
